directory="#{directory.sensitive.path}";
if [ -d $directory ];
  then tar -cf - -C $directory . | gzip --no-name > /tmp/dir_sens_comp;
  hash=$(shasum -a 256 /tmp/dir_sens_comp | cut -d' ' -f1);
  rm -f /tmp/dir_sens_comp;
  if [ "$hash" != "#{directory.sensitive.hash}" ];
    then echo $directory;
  fi;
else echo $directory;
fi;
